/*
 * BlockChainStatus.h
 *
 *  Created on: 30 oct. 2020
 *      Author: Ramiro
 */

#ifndef BLOCKCHAINSTATUS_H_
#define BLOCKCHAINSTATUS_H_

typedef enum{
		STATUS_OK,
		STATUS_CORRUPT_FORMAT,
		STATUS_CORRUPT_FORMAT_BAD_HASH,
		STATUS_CORRUPT_FORMAT_BAD_TXINDEX,
		STATUS_CORRUPT_FORMAT_BAD_TXIN,
		STATUS_CORRUPT_FORMAT_BAD_TXOUT,
		STATUS_CORRUPT_FORMAT_BAD_BTCVALUE,
		STATUS_BAD_ALLOC,
		STATUS_BAD_READ_INPUT_FILE,
		STATUS_BAD_READ_OUTPUT_FILE,
		STATUS_NO_BLOCKS_TO_CONVERT,
		STATUS_FINISH_CONVERT_SUCCESSFULY,
}status_t;




#endif /* BLOCKCHAINSTATUS_H_ */
